<?php

namespace CrochetLibraryBundle\Repository;

/**
 * YarnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YarnRepository extends \Doctrine\ORM\EntityRepository
{
}
